import { DUE_DATE_MONTHS, CHILD_AGES } from './villageData';

export type QuizQuestion = {
  id: string;
  question: string;
  multi: boolean;
  options: string[];
  type?: 'location';
  skipIf?: (answers: Record<string, string[]>) => boolean;
  hasRequestButton?: boolean;
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'born_or_expecting',
    question: 'Do you have children already, or are you expecting?',
    multi: false,
    options: ['My child(ren) are here', "We're expecting", 'Planning / Trying to Conceive (TTC)'],
  },
  {
    id: 'ttc_journey',
    question: 'What best describes your TTC journey? (Select all that apply)',
    multi: true,
    options: [
      'Just starting out',
      'Been trying for 6–12 months',
      'Long journey — trying for 1+ year',
      'Dealing with infertility',
      'PCOS or hormonal condition',
      'Unexplained infertility',
      'Secondary infertility (already have a child)',
      'Currently in fertility treatments (IVF, IUI, etc.)',
      'TTC after a pregnancy loss',
      'LGBTQ+ family building',
      'Prefer not to say',
    ],
    hasRequestButton: true,
    skipIf: (answers) => answers['born_or_expecting']?.[0] !== 'Planning / Trying to Conceive (TTC)',
  },
  {
    id: 'due_date',
    question: 'When is your due date?',
    multi: false,
    options: DUE_DATE_MONTHS,
    skipIf: (answers) => answers['born_or_expecting']?.[0] !== "We're expecting",
  },
  {
    id: 'num_kids',
    question: 'How many children do you have?',
    multi: false,
    options: ['0 / None yet', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'I have more'],
  },
  {
    id: 'family_planning',
    question: 'Are you planning to have more children?',
    multi: false,
    options: [
      'Yes — we want more children',
      "No — we're one and done",
      'No — our family feels complete',
      'Not sure yet / Open to it',
      'Prefer not to say',
    ],
    skipIf: (answers) => answers['born_or_expecting']?.[0] === 'Planning / Trying to Conceive (TTC)',
  },
  {
    id: 'gender',
    question: 'Do you have a girl or boy?',
    multi: true,
    options: ['Girl', 'Boy', 'Other', 'None yet / Not applicable'],
  },
  {
    id: 'gender_identity',
    question: 'How does your child identify?',
    multi: true,
    options: [
      'Non-binary',
      'Transgender Boy (FTM)',
      'Transgender Girl (MTF)',
      'Gender fluid',
      'Questioning / Exploring',
      'Prefer not to say',
    ],
    skipIf: (answers) => !(answers['gender'] ?? []).includes('Other'),
  },
  {
    id: 'multiples',
    question: 'Are any of your children multiples?',
    multi: true,
    options: ['No', 'Twins', 'Triplets', 'Quadruplets', 'Quintuplets', 'I have more'],
  },
  {
    id: 'twins_type',
    question: 'What type of twins do you have? (Select all that apply)',
    multi: true,
    options: ['Identical Twins', 'Fraternal Twins', 'Multiple sets of twins', 'Not sure / Unknown'],
    skipIf: (answers) => !(answers['multiples'] ?? []).includes('Twins'),
  },
  {
    id: 'child_age',
    question: 'How old are your children?',
    multi: true,
    options: CHILD_AGES.map(a => a.label),
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'parent_status',
    question: 'What is your parent status?',
    multi: true,
    options: [
      'Biological Parent',
      'Adoptive Parent',
      'Step-parent',
      'Foster Parent',
    ],
  },
  {
    id: 'familial_situation',
    question: 'Is this a familial foster or adoption situation?',
    multi: true,
    options: [
      'Grandparent raising grandchild(ren)',
      'Aunt / Uncle raising nieces/nephews',
      'Other family member (cousin, sibling, etc.)',
      'Not a familial situation',
    ],
    skipIf: (answers) => {
      const status = answers['parent_status'] ?? [];
      return !status.includes('Foster Parent') && !status.includes('Adoptive Parent');
    },
  },
  {
    id: 'single_parent',
    question: 'Does any of this describe your family situation?',
    multi: true,
    options: [
      'Single Mom by Choice',
      'Single Dad by Choice',
      'Single Mom by Circumstance',
      'Single Dad by Circumstance',
      'Single Mom — Widowed / Loss',
      'Single Dad — Widowed / Loss',
      'Co-parenting',
      'None of these',
    ],
    hasRequestButton: true,
  },
  {
    id: 'lgbtq_family',
    question: 'Do any of these describe your family?',
    multi: true,
    options: [
      'Gay Dads',
      'Lesbian Moms',
      'Queer / Non-Binary Parent(s)',
      'Same-sex couple',
      'Transgender Parent',
      'None of these',
    ],
    hasRequestButton: true,
  },
  {
    id: 'military_family',
    question: 'Is your family connected to the military?',
    multi: true,
    options: [
      'Military Mom (Active Duty)',
      'Military Dad (Active Duty)',
      'Spouse / Partner of Military Member',
      'Veteran Parent',
      'National Guard / Reserve Parent',
      'None of these',
    ],
  },
  {
    id: 'fertility_treatments',
    question: 'Did you use any fertility treatments?',
    multi: true,
    options: [
      'IVF',
      'IUI',
      'Donor Egg / Sperm',
      'Embryo Donation',
      'Surrogacy',
      'No fertility treatments',
    ],
  },
  {
    id: 'parent_age_range',
    question: 'How old are you?',
    multi: false,
    options: [
      'Under 20',
      '20–24',
      '25–29',
      '30–34',
      '35–39',
      '40–44',
      '45+',
      'Prefer not to say',
    ],
  },
  {
    id: 'loss_parent',
    question: 'Have you experienced the loss of a child or pregnancy?',
    multi: false,
    options: ['Yes', 'No', "I'd rather not say"],
  },
  {
    id: 'loss_type',
    question: 'How did you experience this loss? (Select all that apply)',
    multi: true,
    options: [
      'Miscarriage (1st trimester)',
      'Miscarriage (2nd trimester)',
      'Ectopic or molar pregnancy',
      'TFMR (Termination for Medical Reasons)',
      'Stillbirth (20+ weeks)',
      'Loss shortly after birth (NICU / prematurity complications)',
      'SIDS (Sudden Infant Death Syndrome)',
      'SUDC (Sudden Unexplained Death in Childhood)',
      'SADS (Sudden Arrhythmia Death Syndrome)',
      'Illness or medical condition',
      'Pediatric cancer',
      'Accident or injury',
      "I'd rather not say",
    ],
    hasRequestButton: true,
    skipIf: (answers) => answers['loss_parent']?.[0] !== 'Yes',
  },
  {
    id: 'gestational_age',
    question: 'What was your child\'s gestational age at birth?',
    multi: false,
    options: [
      'Under 22 weeks (Periviable)',
      '22–24 weeks (Extreme Prematurity)',
      '25–32 weeks (Moderate Prematurity)',
      '33–36 weeks (Late Preterm)',
      '37+ weeks / Full term',
    ],
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'nicu_experience',
    question: 'Did your child spend time in the NICU?',
    multi: false,
    options: ['Yes — they were in the NICU', 'No', 'Prefer not to say'],
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'birth_type',
    question: 'What type of birth did you have / are you planning? (Select all that apply)',
    multi: true,
    options: [
      'Vaginal birth',
      'Unmedicated / natural birth',
      'Planned C-section',
      'Emergency C-section',
      'VBAC (Vaginal Birth After Cesarean)',
      'Home birth',
      'Birth center birth',
      'Water birth',
      'Induced labor',
      'Assisted delivery (forceps or vacuum)',
      'Experienced birth trauma',
      'Still planning / not yet decided',
      'Prefer not to say',
    ],
    hasRequestButton: true,
    skipIf: (answers) =>
      answers['born_or_expecting']?.[0] === 'Planning / Trying to Conceive (TTC)' &&
      (answers['num_kids']?.[0] === '0 / None yet' || !answers['num_kids']?.[0]),
  },
  {
    id: 'birth_csection_detail',
    question: 'Tell us more about your C-section experience:',
    multi: true,
    options: [
      'Planned due to medical recommendation (breech, placenta previa, etc.)',
      'Planned by personal choice',
      'Emergency due to fetal distress',
      'Emergency due to failure to progress',
      'Emergency due to placenta complications',
      'Emergency due to cord prolapse or other emergency',
      'Repeat C-section (not my first)',
      'Difficult recovery',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const b = answers['birth_type'] ?? [];
      return !b.includes('Planned C-section') && !b.includes('Emergency C-section');
    },
  },
  {
    id: 'birth_vbac_detail',
    question: 'Tell us more about your VBAC:',
    multi: true,
    options: [
      'Successful VBAC — vaginal birth achieved',
      'Attempted VBAC that ended in C-section',
      'Planning a VBAC for an upcoming birth',
      'VBAC after 1 C-section',
      'VBAC after 2 or more C-sections',
    ],
    skipIf: (answers) => !(answers['birth_type'] ?? []).includes('VBAC (Vaginal Birth After Cesarean)'),
  },
  {
    id: 'birth_trauma_detail',
    question: 'What best describes your birth trauma experience? (Select all that apply)',
    multi: true,
    options: [
      'Traumatic emergency C-section',
      'Postpartum hemorrhage',
      'Medical emergency during or after delivery',
      'Baby transferred to NICU immediately after birth',
      'Feeling unheard or unsupported during labor',
      'Loss of my planned birth experience',
      'Birth-related PTSD or anxiety',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const b = answers['birth_type'] ?? [];
      return !b.includes('Emergency C-section') && !b.includes('Experienced birth trauma');
    },
  },
  {
    id: 'neuro_dev',
    question: 'Does your child have any neurodevelopmental differences?',
    multi: true,
    options: [
      'Autism Level 1',
      'Autism Level 2',
      'Autism Level 3',
      'ADHD',
      'Learning Disability',
      'Sensory Processing Differences',
      'None / Not applicable',
    ],
    hasRequestButton: true,
  },
  {
    id: 'autism_l1_girl_type',
    question: 'How was your child\'s Autism Level 1 identified?',
    multi: false,
    options: ['Standard Diagnosis', 'Late / Missed Diagnosis'],
    skipIf: (answers) =>
      !(answers['neuro_dev'] ?? []).includes('Autism Level 1'),
  },
  {
    id: 'adhd_type',
    question: 'Which type of ADHD does your child have?',
    multi: false,
    options: [
      'Inattentive Type (ADD)',
      'Hyperactive-Impulsive Type',
      'Combined Type',
      'Awaiting / Unsure of Diagnosis',
    ],
    skipIf: (answers) => !(answers['neuro_dev'] ?? []).includes('ADHD'),
  },
  {
    id: 'learning_disability_type',
    question: 'Which learning disability does your child have?',
    multi: true,
    options: [
      'Dyslexia',
      'Dyscalculia',
      'Dysgraphia',
      'Dyspraxia / Developmental Coordination Disorder',
      'Auditory Processing Disorder',
      'Nonverbal Learning Disability (NVLD)',
      'Other Learning Disability',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['neuro_dev'] ?? []).includes('Learning Disability'),
  },
  {
    id: 'spd_type',
    question: 'Which sensory differences does your child experience?',
    multi: true,
    options: [
      'Tactile sensitivity (touch / textures)',
      'Auditory sensitivity (sounds)',
      'Visual sensitivity (light / motion)',
      'Oral / gustatory sensitivity (taste / food textures)',
      'Olfactory sensitivity (smells)',
      'Proprioceptive differences (body awareness / pressure)',
      'Vestibular differences (balance / movement)',
      'Interoceptive differences (internal body sensations)',
      'Sensory seeking',
      'Sensory avoidance',
      'Mixed / multiple sensory differences',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['neuro_dev'] ?? []).includes('Sensory Processing Differences'),
  },
  {
    id: 'medical_diagnosis',
    question: 'Does your child have any of the following medical diagnoses?',
    multi: true,
    options: [
      'Down Syndrome',
      'Cerebral Palsy',
      'Congenital Heart Defect',
      'Genetic / Chromosomal Condition',
      'Premature Birth',
      'Pediatric Cancer',
      'Kidney / Urological Condition',
      'Craniosynostosis',
      'Other Medical Condition',
      'None of these',
    ],
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'ds_subtype',
    question: 'Which type of Down Syndrome does your child have?',
    multi: true,
    options: ['Trisomy 21 (Standard)', 'Translocation', 'Mosaic', 'Dual Diagnosis'],
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Down Syndrome'),
  },
  {
    id: 'cp_subtype',
    question: 'Which type of Cerebral Palsy does your child have?',
    multi: true,
    options: [
      'Hemiplegia — Left Side',
      'Hemiplegia — Right Side',
      'Diplegia',
      'Quadriplegia',
      'Ataxic CP',
      'Dyskinetic / Athetoid CP',
    ],
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Cerebral Palsy'),
  },
  {
    id: 'chd_type',
    question: 'Which type of congenital heart defect does your child have?',
    multi: true,
    options: [
      'HLHS (Hypoplastic Left Heart Syndrome)',
      'Tetralogy of Fallot',
      'Transposition of the Great Arteries (TGA)',
      'Ventricular Septal Defect (VSD)',
      'Atrial Septal Defect (ASD)',
      'Coarctation of the Aorta',
      'Pulmonary Atresia',
      'AVSD (Atrioventricular Septal Defect)',
      'Other Congenital Heart Defect',
    ],
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Congenital Heart Defect'),
  },
  {
    id: 'genetic_condition',
    question: 'Which genetic or chromosomal condition does your child have?',
    multi: true,
    options: [
      'Fragile X Syndrome',
      'Rett Syndrome',
      'Prader-Willi Syndrome',
      'Angelman Syndrome',
      'Tuberous Sclerosis Complex',
      '22q11.2 Deletion / DiGeorge Syndrome',
      'Williams Syndrome',
      'Ehlers-Danlos Syndrome (EDS)',
      'CHARGE Syndrome',
      'Other Genetic / Chromosomal Condition',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Genetic / Chromosomal Condition'),
  },
  {
    id: 'other_medical_condition',
    question: 'Which medical condition does your child have?',
    multi: true,
    options: [
      'Spina Bifida',
      'Hydrocephalus',
      'Epilepsy / Seizure Disorder',
      'Type 1 Diabetes',
      'Cystic Fibrosis',
      'Spinal Muscular Atrophy (SMA)',
      'Muscular Dystrophy',
      'Sickle Cell Disease',
      'Cleft Lip / Palate',
      'Osteogenesis Imperfecta',
      'Esophageal Atresia / Tracheoesophageal Fistula (TEF)',
      'Gastroschisis / Omphalocele',
      "Hirschsprung's Disease",
      'Biliary Atresia',
      'Short Bowel Syndrome',
      'Scoliosis',
      'Hip Dysplasia (DDH)',
      'Other',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Other Medical Condition'),
  },
  {
    id: 'pediatric_cancer_type',
    question: 'What type of cancer does / did your child have?',
    multi: true,
    options: [
      'Leukemia (ALL or AML)',
      'Brain tumor',
      'Lymphoma',
      'Neuroblastoma',
      "Wilms tumor (kidney)",
      'Bone cancer (Osteosarcoma or Ewing Sarcoma)',
      'Soft tissue sarcoma (Rhabdomyosarcoma, etc.)',
      'Retinoblastoma',
      'Liver tumor (Hepatoblastoma)',
      'Childhood cancer survivor',
      'Other pediatric cancer',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Pediatric Cancer'),
  },
  {
    id: 'kidney_condition_type',
    question: "What best describes your child's kidney or urological condition?",
    multi: true,
    options: [
      'Hydronephrosis',
      'Vesicoureteral Reflux (VUR)',
      'Polycystic Kidney Disease (PKD)',
      'Nephrotic Syndrome',
      'Chronic Kidney Disease (CKD)',
      'Kidney transplant',
      'Posterior Urethral Valves (PUV)',
      'Other kidney / urological condition',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['medical_diagnosis'] ?? []).includes('Kidney / Urological Condition'),
  },
  {
    id: 'medical_equipment',
    question: 'Does your child use any medical equipment?',
    multi: true,
    options: [
      'Feeding tube (G-tube, NG-tube, GJ-tube, etc.)',
      'Wheelchair or power chair',
      'Gait trainer / adaptive walker',
      'Hearing aids',
      'Cochlear implant',
      'Tracheostomy (trach)',
      'Oxygen / respiratory support',
      'Communication device (AAC / speech-generating device)',
      'Insulin pump or CGM (continuous glucose monitor)',
      'Orthotics / AFOs / leg braces / prosthetics',
      'CPAP / BiPAP',
      'None of these',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'equipment_wheelchair_detail',
    question: 'What type of mobility equipment does your child use?',
    multi: true,
    options: [
      'Manual wheelchair',
      'Power wheelchair / power chair',
      'Gait trainer / pediatric walker',
      'Stander / standing frame',
      'Uses multiple mobility devices',
    ],
    skipIf: (answers) => {
      const e = answers['medical_equipment'] ?? [];
      return !e.includes('Wheelchair or power chair') && !e.includes('Gait trainer / adaptive walker');
    },
  },
  {
    id: 'equipment_hearing_detail',
    question: "What best describes your child's hearing situation?",
    multi: true,
    options: [
      'Hearing aids (mild to moderate hearing loss)',
      'Cochlear implant — one ear',
      'Bilateral cochlear implants — both ears',
      'Bone anchored hearing aid (BAHA / Osia)',
      'Profound deafness — no amplification device',
      'Hard of hearing — navigating without devices',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const e = answers['medical_equipment'] ?? [];
      return !e.includes('Hearing aids') && !e.includes('Cochlear implant');
    },
  },
  {
    id: 'equipment_oxygen_detail',
    question: "What does your child's respiratory support look like?",
    multi: true,
    options: [
      'Home oxygen — continuous use',
      'Oxygen during sleep or activity only',
      'High-flow nasal cannula',
      'Tracheostomy (trach) — with or without vent',
      'Ventilator (vent) dependent',
      'Pulse oximetry monitoring only',
    ],
    skipIf: (answers) => {
      const e = answers['medical_equipment'] ?? [];
      return !e.includes('Oxygen / respiratory support') && !e.includes('Tracheostomy (trach)');
    },
  },
  {
    id: 'child_surgery',
    question: 'Has your child had surgery?',
    multi: true,
    options: [
      'Yes — already had surgery',
      'Surgery scheduled / upcoming',
      'No',
      'Prefer not to say',
    ],
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'child_surgery_type',
    question: 'What type(s) of surgery has your child had or is scheduled for? (Select all that apply)',
    multi: true,
    options: [
      'Open heart surgery',
      'Cardiac catheterization',
      'Brain / neurosurgery (shunt, tumor removal, etc.)',
      'Craniosynostosis repair (skull surgery)',
      'Spinal surgery (fusion, tethered cord release, etc.)',
      'Orthopedic surgery (hip, clubfoot, leg lengthening, etc.)',
      'Abdominal / GI surgery',
      'Airway surgery (tracheostomy, laryngoscopy, etc.)',
      'Ear tubes (tympanostomy)',
      'Cochlear implant surgery',
      'Eye surgery (strabismus, etc.)',
      'Cleft lip or palate repair',
      'Feeding tube placement (G-tube, etc.)',
      'Kidney or urological surgery',
      'Tumor or cancer surgery',
      'Organ transplant',
      'Multiple / complex surgeries',
      'Other surgery',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const s = answers['child_surgery'] ?? [];
      return !s.includes('Yes — already had surgery') && !s.includes('Surgery scheduled / upcoming');
    },
  },
  {
    id: 'feeding_method',
    question: 'How does your child eat?',
    multi: true,
    options: [
      'Breastfeeding',
      'Formula feeding',
      'Exclusive pumping',
      'Combination feeding',
      'Tube feeding (G-tube, GJ-tube, NG-tube)',
      'Eating solids',
      'None / Not applicable',
    ],
  },
  {
    id: 'breastfeeding_detail',
    question: 'Tell us more about your breastfeeding journey:',
    multi: true,
    options: [
      'Over supplier',
      'Just enougher',
      'Low supply / Under supplier',
      'Extended breastfeeding (1+ year)',
      'Weaning',
      'Nursing strike',
      'Prefer not to say',
    ],
    skipIf: (answers) => !(answers['feeding_method'] ?? []).includes('Breastfeeding'),
  },
  {
    id: 'formula_detail',
    question: 'Which type of formula does your child use?',
    multi: true,
    options: [
      'Standard formula (no issues)',
      'Specialty formula needed',
      'Hypoallergenic formula (e.g. Nutramigen, Alimentum)',
      'Amino acid formula (e.g. Elecare, Neocate)',
      'Donor breast milk',
      'Prefer not to say',
    ],
    skipIf: (answers) => !(answers['feeding_method'] ?? []).includes('Formula feeding'),
  },
  {
    id: 'pumping_detail',
    question: 'Tell us more about your pumping journey:',
    multi: true,
    options: [
      'Over supplier',
      'Just enougher',
      'Low supply / Under supplier',
      'Using a hospital-grade / rental pump',
      'Prefer not to say',
    ],
    skipIf: (answers) => !(answers['feeding_method'] ?? []).includes('Exclusive pumping'),
  },
  {
    id: 'tube_feeding_detail',
    question: 'Which type of tube feeding does your child have?',
    multi: true,
    options: [
      'G-tube (gastrostomy tube)',
      'GJ-tube (gastrojejunostomy tube)',
      'NG-tube (nasogastric tube)',
      'NJ-tube (nasojejunal tube)',
      'J-tube (jejunostomy tube)',
      'Transitioning off tube feeding',
      'Prefer not to say',
    ],
    skipIf: (answers) => !(answers['feeding_method'] ?? []).includes('Tube feeding (G-tube, GJ-tube, NG-tube)'),
  },
  {
    id: 'solids_detail',
    question: 'Tell us more about your child and solid foods:',
    multi: true,
    options: [
      'Just starting solids (4–6 months)',
      'Baby-led weaning (BLW)',
      'Puree / spoon feeding',
      'Toddler eating (finger foods)',
      'Food allergies / intolerances',
      'Extreme picky eating',
      'Oral aversion / food refusal',
      'Prefer not to say',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['feeding_method'] ?? []).includes('Eating solids'),
  },
  {
    id: 'sleep_challenges',
    question: 'Does your child have any sleep challenges? (Select all that apply)',
    multi: true,
    options: [
      'Difficulty falling asleep / sleep onset struggles',
      'Frequent night wakings',
      'Early morning waking (before 6am)',
      'Short naps / nap refusal',
      'Sleep regressions',
      'Night terrors or nightmares',
      'Co-sleeping / bedsharing',
      'Currently sleep training (or recently completed)',
      'No significant sleep challenges',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'sleep_training_method',
    question: 'Which sleep training approach are you using or have you used?',
    multi: true,
    options: [
      'Ferber method / graduated extinction',
      'Full extinction / Cry It Out (CIO)',
      'Chair method / Sleep Lady Shuffle',
      'Pick Up Put Down (PUPD)',
      'No Cry Sleep Solution',
      'Gentle / attachment-based approach',
      'Working with a sleep consultant',
    ],
    hasRequestButton: true,
    skipIf: (answers) =>
      !(answers['sleep_challenges'] ?? []).includes('Currently sleep training (or recently completed)'),
  },
  {
    id: 'sleep_cosleeping_detail',
    question: 'What best describes your co-sleeping or bedsharing situation?',
    multi: true,
    options: [
      'Intentional bedsharing (same bed, by choice)',
      'Room sharing — baby on a separate surface in our room',
      'Side-car / bassinet pulled up to our bed',
      'Child comes to our bed during the night',
      'Transitioning out of our bed',
    ],
    skipIf: (answers) =>
      !(answers['sleep_challenges'] ?? []).includes('Co-sleeping / bedsharing'),
  },
  {
    id: 'mental_health',
    question: 'Are you experiencing any mental health challenges? (Select all that apply)',
    multi: true,
    options: [
      'Postpartum depression (PPD)',
      'Postpartum anxiety (PPA)',
      'Postpartum OCD',
      'Postpartum rage',
      'Postpartum psychosis (survivor)',
      'Prenatal / antepartum depression or anxiety',
      'Birth trauma or PTSD',
      'Caregiver burnout',
      'Grief from pregnancy or infant loss',
      'General parental anxiety or depression',
      'Chronic or pre-existing mental health condition',
      'Seeking support / not sure what I\'m experiencing',
      'No current mental health challenges',
      'Prefer not to say',
    ],
    hasRequestButton: true,
  },
  {
    id: 'mental_health_ppd_ppa_detail',
    question: 'Tell us more about where you are in your PPD / PPA journey:',
    multi: true,
    options: [
      'Currently experiencing it',
      'In treatment / seeing a provider',
      'On medication',
      'In recovery / reflecting on my journey',
      'Paternal / non-birthing partner experiencing PPD or PPA',
      'Struggling to get a diagnosis or find support',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const mh = answers['mental_health'] ?? [];
      return !mh.includes('Postpartum depression (PPD)') && !mh.includes('Postpartum anxiety (PPA)');
    },
  },
  {
    id: 'dietary_restrictions',
    question: 'Does your family have any dietary restrictions or food needs?',
    multi: true,
    options: [
      'Food allergies',
      'Special diet (vegan, vegetarian, kosher, halal, etc.)',
      'Medical diet (celiac, diabetic, elimination diet, etc.)',
      'No dietary restrictions',
      'Prefer not to say',
    ],
    hasRequestButton: true,
  },
  {
    id: 'dietary_allergies_detail',
    question: 'Which food allergies does your family manage? (Select all that apply)',
    multi: true,
    options: [
      'Peanut allergy',
      'Tree nut allergy',
      'Milk / dairy allergy',
      'Egg allergy',
      'Wheat / gluten allergy',
      'Soy allergy',
      'Fish or shellfish allergy',
      'Sesame allergy',
      'Multiple food allergies',
      'Anaphylactic / severe allergy (epi-pen required)',
      'Eosinophilic Esophagitis (EoE)',
      'FPIES (Food Protein-Induced Enterocolitis Syndrome)',
      'Other food allergy',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['dietary_restrictions'] ?? []).includes('Food allergies'),
  },
  {
    id: 'dietary_special_detail',
    question: 'What type of special or medical diet does your family follow? (Select all that apply)',
    multi: true,
    options: [
      'Gluten-free (celiac or non-celiac sensitivity)',
      'Dairy-free',
      'Vegan',
      'Vegetarian',
      'Kosher',
      'Halal',
      'Keto / low-carb',
      'Paleo',
      'AIP (Autoimmune Protocol)',
      'Elimination diet',
      'GAPS or SCD diet',
      'Low-sugar / diabetic management diet',
      'Other special diet',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const d = answers['dietary_restrictions'] ?? [];
      return !d.includes('Special diet (vegan, vegetarian, kosher, halal, etc.)') &&
             !d.includes('Medical diet (celiac, diabetic, elimination diet, etc.)');
    },
  },
  {
    id: 'challenges_main',
    question: 'What are your biggest challenges right now? (Select all that apply)',
    multi: true,
    options: [
      'Feeding difficulties',
      'Sleep challenges',
      'Behavioral challenges',
      'Medical appointments / therapies',
      'Finding childcare',
      'Financial strain',
      'Isolation / lack of support',
      'Navigating systems (school, medical, insurance)',
      'Development & milestones',
      'None of these',
    ],
    hasRequestButton: true,
  },
  {
    id: 'challenges_feeding_detail',
    question: 'Which feeding challenges are you navigating?',
    multi: true,
    options: [
      'ARFID (Avoidant / Restrictive Food Intake Disorder)',
      'Tube weaning',
      'Feeding therapy',
      'Oral aversion / food refusal',
      'Failure to thrive / growth concerns',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Feeding difficulties'),
  },
  {
    id: 'challenges_sleep_detail',
    question: 'Which sleep challenges are you navigating?',
    multi: true,
    options: [
      'Sleep training',
      'Night waking / wakeful sleeper',
      'Sleep regressions',
      'Co-sleeping / bedsharing',
      'Early rising',
      'Night terrors / nightmares',
    ],
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Sleep challenges'),
  },
  {
    id: 'challenges_behavior_detail',
    question: 'Which behavioral challenges are you navigating?',
    multi: true,
    options: [
      'Tantrums & meltdowns',
      'Oppositional behavior (ODD)',
      'Aggression',
      'ABA therapy journey',
      'Child anxiety',
      'School refusal',
      'Self-injurious behavior',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Behavioral challenges'),
  },
  {
    id: 'challenges_medical_detail',
    question: 'Which medical / therapy challenges are you navigating?',
    multi: true,
    options: [
      'High appointment load (10+ per year)',
      'Multiple therapies (OT, PT, SLP, etc.)',
      'Awaiting a diagnosis',
      'Medically complex / fragile child',
      'Home health nursing involved',
    ],
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Medical appointments / therapies'),
  },
  {
    id: 'challenges_childcare_detail',
    question: 'Which childcare challenges are you navigating?',
    multi: true,
    options: [
      'Finding childcare for a child with special needs',
      'Finding an inclusive daycare or school',
      'Long waitlists / no availability',
      'Caregiver burnout',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Finding childcare'),
  },
  {
    id: 'challenges_financial_detail',
    question: 'Which financial challenges are you navigating?',
    multi: true,
    options: [
      'Medical bills / out-of-pocket costs',
      'Therapy costs not covered by insurance',
      'SSI / disability benefits navigation',
      'Food or housing instability',
      'FMLA / disability leave navigation',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Financial strain'),
  },
  {
    id: 'challenges_isolation_detail',
    question: 'What makes you feel isolated or unsupported?',
    multi: true,
    options: [
      'Hard to find other parents in my situation',
      'Geographic isolation (rural / remote area)',
      'Single parent without a support system',
      'Looking for online-only support',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Isolation / lack of support'),
  },
  {
    id: 'challenges_systems_detail',
    question: 'Which systems are you navigating?',
    multi: true,
    options: [
      'IEP / special education at school',
      'Insurance denials / appeals',
      'Medical records / care coordination',
      'State waiver programs (Medicaid waiver, etc.)',
      'FMLA / disability leave',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Navigating systems (school, medical, insurance)'),
  },
  {
    id: 'challenges_development_detail',
    question: 'Which developmental challenges are you navigating?',
    multi: true,
    options: [
      'Speech delay',
      'Developmental delay',
      'Gross motor / walking delays',
      'Potty training struggles',
      'Gifted child / twice exceptional',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['challenges_main'] ?? []).includes('Development & milestones'),
  },
  {
    id: 'school_type',
    question: 'What type of school or childcare does your child attend?',
    multi: true,
    options: [
      'Public school (K–12)',
      'Private school (K–12)',
      'Homeschool / Home education',
      'Daycare / Childcare center',
      'Preschool / Pre-K program',
      'In-home childcare (nanny, au pair, or family member)',
      'Not in school or childcare yet',
      'None of these / Other',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'school_public_detail',
    question: "What best describes your child's public school experience?",
    multi: true,
    options: [
      'General education / mainstream classroom',
      'IEP — special education services',
      'Inclusion classroom (general ed with supports)',
      'Self-contained special education classroom',
      'Magnet school',
      'Charter school',
      'Title I / high-need school',
      'Virtual / online public school',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['school_type'] ?? []).includes('Public school (K–12)'),
  },
  {
    id: 'school_private_detail',
    question: 'What type of private school does your child attend?',
    multi: false,
    options: [
      'Secular / academic private school',
      'Faith-based / religious school',
      'Montessori school',
      'Waldorf school',
      'Private special education school',
      'College prep or boarding school',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['school_type'] ?? []).includes('Private school (K–12)'),
  },
  {
    id: 'school_homeschool_detail',
    question: 'What homeschool style or approach do you use?',
    multi: true,
    options: [
      'Classical education',
      'Charlotte Mason method',
      'Unschooling / child-led learning',
      'Eclectic / mix of methods',
      'Online / virtual (hybrid homeschool)',
      'Homeschool co-op',
      'Homeschooling due to special needs or medical needs',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['school_type'] ?? []).includes('Homeschool / Home education'),
  },
  {
    id: 'school_childcare_detail',
    question: 'What best describes your childcare or preschool setting?',
    multi: false,
    options: [
      'Large daycare center',
      'Small home daycare / family childcare',
      'Employer-sponsored or corporate daycare',
      'Faith-based / church daycare or preschool',
      'Head Start / Early Head Start program',
      'Montessori preschool',
      'Military CDC (Child Development Center)',
      'Nanny (in-home caregiver)',
      'Au pair',
      'Grandparent or family member',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const s = answers['school_type'] ?? [];
      return !s.includes('Daycare / Childcare center') &&
             !s.includes('Preschool / Pre-K program') &&
             !s.includes('In-home childcare (nanny, au pair, or family member)');
    },
  },
  {
    id: 'iep_504',
    question: 'Does your child have an IEP or 504 plan?',
    multi: true,
    options: [
      'IEP (Individualized Education Program)',
      '504 Plan',
      'Early Intervention (under age 3 — Part C)',
      'In process of getting an evaluation',
      "My child was denied — I'm fighting for services",
      'Neither — general education',
      'Not applicable / too young',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'iep_services_detail',
    question: "What does your child's IEP primarily cover? (Select all that apply)",
    multi: true,
    options: [
      'Speech-Language (SLP) services',
      'Occupational Therapy (OT) services',
      'Physical Therapy (PT) services',
      'Behavioral support / Behavior Intervention Plan (BIP)',
      'Academic accommodations and modifications',
      'Autism services',
      'Intellectual disability support',
      'Multiple / complex needs',
      'Extended School Year (ESY) services',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['iep_504'] ?? []).includes('IEP (Individualized Education Program)'),
  },
  {
    id: 'iep_504_plan_detail',
    question: "What does your child's 504 plan primarily address?",
    multi: true,
    options: [
      'ADHD-related accommodations (extra time, movement breaks, etc.)',
      'Anxiety or mental health needs',
      'Physical or medical needs (diabetes, seizures, allergies, etc.)',
      'Sensory accommodations',
      'Reading or writing accommodations',
      'Other accommodations',
    ],
    skipIf: (answers) => !(answers['iep_504'] ?? []).includes('504 Plan'),
  },
  {
    id: 'iep_process_detail',
    question: 'Where are you in the evaluation or advocacy process?',
    multi: true,
    options: [
      'Just requested an evaluation',
      'Evaluation scheduled or currently underway',
      'Waiting for eligibility determination',
      'Navigating a denial or disagreement with the school',
      'Seeking a private / independent evaluation',
      'Filing a complaint or going to due process',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const p = answers['iep_504'] ?? [];
      return !p.includes('In process of getting an evaluation') &&
             !p.includes("My child was denied — I'm fighting for services");
    },
  },
  {
    id: 'child_therapy',
    question: 'Does your child attend therapy?',
    multi: true,
    options: [
      'Yes — private therapy outside of school',
      'School-based services only (IEP / IFSP)',
      'Both private and school-based therapy',
      'On a waitlist for therapy',
      'No therapy currently',
      'We completed therapy / graduated',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const boe = answers['born_or_expecting']?.[0];
      const numKids = answers['num_kids']?.[0];
      return (boe === "We're expecting" && numKids === '1') ||
             (boe === 'Planning / Trying to Conceive (TTC)' && (numKids === '0 / None yet' || !numKids));
    },
  },
  {
    id: 'child_therapy_private_types',
    question: 'What types of private therapy does your child receive? (Select all that apply)',
    multi: true,
    options: [
      'Speech-Language Therapy (SLP)',
      'Occupational Therapy (OT)',
      'Physical Therapy (PT)',
      'ABA (Applied Behavior Analysis)',
      'Feeding therapy',
      'Developmental therapy',
      'Vision therapy',
      'Child psychologist / mental health therapy',
      'Social skills group',
      'Play therapy',
      'Music therapy',
      'Aquatic therapy',
      'Hippotherapy / equine therapy',
      'Other private therapy',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const t = answers['child_therapy'] ?? [];
      return !t.includes('Yes — private therapy outside of school') &&
             !t.includes('Both private and school-based therapy');
    },
  },
  {
    id: 'work_status',
    question: 'Do you currently work?',
    multi: false,
    options: [
      'Yes — full time',
      'Yes — part time',
      "No — I'm a stay at home parent",
      'On leave / between jobs',
    ],
  },
  {
    id: 'work_situation',
    question: 'What best describes the type of work you do? (Select all that apply)',
    multi: true,
    options: [
      'Night shift worker',
      'Healthcare worker',
      'Teacher / Educator',
      'Work from home / Remote',
      'Self-employed / Entrepreneur / Business owner',
      'Working multiple jobs',
      'None of these / Other',
    ],
    hasRequestButton: true,
    skipIf: (answers) => {
      const status = answers['work_status']?.[0];
      return status === "No — I'm a stay at home parent" || status === 'On leave / between jobs';
    },
  },
  {
    id: 'work_night_detail',
    question: 'What kind of night shift do you work?',
    multi: true,
    options: [
      'Healthcare / Hospital',
      'Hospitality / Food & beverage service',
      'Security / Law enforcement',
      'Transportation / Logistics',
      'Factory / Warehouse',
      'Other night shift',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['work_situation'] ?? []).includes('Night shift worker'),
  },
  {
    id: 'work_healthcare_detail',
    question: 'What is your healthcare role?',
    multi: true,
    options: [
      'Registered Nurse (RN)',
      'LPN / CNA / Medical aide',
      'Doctor / Physician / Surgeon',
      'Paramedic / EMT / First Responder',
      'Mental health professional (therapist, counselor, psychologist)',
      'Physical / Occupational / Speech Therapist',
      'Pharmacist',
      'Medical admin / Support staff',
      'Other healthcare role',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['work_situation'] ?? []).includes('Healthcare worker'),
  },
  {
    id: 'work_teacher_detail',
    question: 'What level do you teach?',
    multi: true,
    options: [
      'Early childhood / Preschool',
      'Elementary school (K–5)',
      'Middle school (6–8)',
      'High school (9–12)',
      'Special education',
      'College / University',
      'Instructional aide / Paraprofessional',
      'Other educator role',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['work_situation'] ?? []).includes('Teacher / Educator'),
  },
  {
    id: 'work_wfh_detail',
    question: 'What best describes your work from home situation?',
    multi: true,
    options: [
      'Remote employee (company job done remotely)',
      'Freelancer / Independent contractor',
      'Entrepreneur / Business owner',
      'Content creator / Influencer',
      'Home childcare provider / Home daycare',
      'Other WFH situation',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['work_situation'] ?? []).includes('Work from home / Remote'),
  },
  {
    id: 'work_selfemployed_detail',
    question: 'What best describes your business or self-employment?',
    multi: true,
    options: [
      'Small business owner (local / brick & mortar)',
      'Online business / e-commerce',
      'Freelancer / Independent contractor',
      'Content creator / Influencer / Blogger',
      'Consultant or coach',
      'Other self-employment',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['work_situation'] ?? []).includes('Self-employed / Entrepreneur / Business owner'),
  },
  {
    id: 'work_sahp_detail',
    question: 'What best describes your SAHP situation?',
    multi: true,
    options: [
      'By choice — preferred arrangement',
      'Due to childcare costs',
      "Due to child's medical or special needs",
      'Recently transitioned / new to SAHP life',
      'Planning to return to work soon',
    ],
    hasRequestButton: true,
    skipIf: (answers) => answers['work_status']?.[0] !== "No — I'm a stay at home parent",
  },
  {
    id: 'work_multiple_jobs_detail',
    question: 'What best describes your situation?',
    multi: true,
    options: [
      'Working two jobs (full-time + part-time)',
      'Working three or more jobs',
      'Gig work / Rideshare / Delivery',
      'Side hustle alongside main job',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['work_situation'] ?? []).includes('Working multiple jobs'),
  },
  {
    id: 'insurance_type',
    question: 'What type of health insurance does your family have?',
    multi: true,
    options: [
      'Medicaid / CHIP',
      'Private insurance (employer or marketplace)',
      'TRICARE (military)',
      'Uninsured / No coverage',
      'Medicaid waiver',
      'Not sure / Other',
    ],
  },
  {
    id: 'insurance_medicaid_detail',
    question: 'What are you navigating with Medicaid / CHIP?',
    multi: true,
    options: [
      'Medicaid for my child (CHIP)',
      'Medicaid for parent(s) too',
      'Medicaid denials or appeals',
      'Finding Medicaid-accepting providers',
      'Transitioning off Medicaid due to income changes',
      'Medicaid renewals / redeterminations',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['insurance_type'] ?? []).includes('Medicaid / CHIP'),
  },
  {
    id: 'insurance_private_detail',
    question: 'What are you navigating with private insurance?',
    multi: true,
    options: [
      'Employer-sponsored plan',
      'ACA / Marketplace plan',
      'Insurance denials for therapy or treatments',
      'Out-of-network providers or costs',
      'High deductibles or out-of-pocket costs',
      'COBRA / between jobs coverage',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['insurance_type'] ?? []).includes('Private insurance (employer or marketplace)'),
  },
  {
    id: 'insurance_tricare_detail',
    question: 'What type of TRICARE do you have?',
    multi: true,
    options: [
      'TRICARE Prime',
      'TRICARE Select',
      'TRICARE for Life',
      'TRICARE Reserve Select',
      'TRICARE ECHO (Extended Care Health Option — for special needs)',
      'Still figuring out our TRICARE coverage',
    ],
    skipIf: (answers) => !(answers['insurance_type'] ?? []).includes('TRICARE (military)'),
  },
  {
    id: 'insurance_uninsured_detail',
    question: 'What resources are you looking for?',
    multi: true,
    options: [
      'Applying for Medicaid or CHIP',
      'Free clinic or community health resources',
      'Prescription assistance programs',
      'Navigating coverage gaps between jobs',
      'Looking for affordable coverage options',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['insurance_type'] ?? []).includes('Uninsured / No coverage'),
  },
  {
    id: 'insurance_waiver_detail',
    question: 'Which Medicaid waiver do you have or are pursuing?',
    multi: true,
    options: [
      'HCBS (Home and Community-Based Services) waiver',
      'Katie Beckett / TEFRA waiver',
      'DD (Developmental Disabilities) waiver',
      'Autism waiver',
      'Technology-Assisted waiver (vent / medical equipment)',
      'On the waiver waitlist',
      'Still figuring out which waiver applies',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['insurance_type'] ?? []).includes('Medicaid waiver'),
  },
  {
    id: 'support_network',
    question: 'How would you describe your local support network?',
    multi: true,
    options: [
      'Strong local family support',
      'Limited local support',
      'No local family — friends are my village',
      'Completely isolated / no support network',
      'Long-distance family support only',
    ],
    hasRequestButton: true,
  },
  {
    id: 'support_limited_detail',
    question: 'What best describes your situation?',
    multi: true,
    options: [
      'Recently relocated / new to the area',
      'Estranged from family',
      "Family doesn't understand my child's needs",
      'Rural or remote area',
      'Everyone is too busy / schedules never align',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['support_network'] ?? []).includes('Limited local support'),
  },
  {
    id: 'support_isolated_detail',
    question: "What's contributing to your isolation?",
    multi: true,
    options: [
      'Recently relocated / no roots here yet',
      'Postpartum depression or mental health challenges',
      "Child's complex needs limit outings and activities",
      'Rural or remote location',
      'Partner works away or travels frequently',
      'Grief or major life transition',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['support_network'] ?? []).includes('Completely isolated / no support network'),
  },
  {
    id: 'support_long_distance_detail',
    question: 'What best describes your long-distance situation?',
    multi: true,
    options: [
      'Military life / frequent moves',
      'Moved for work or partner\'s career',
      'Immigrated away from home country',
      'Family is supportive but geographically far',
      'Primary support is virtual (video calls, texts)',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['support_network'] ?? []).includes('Long-distance family support only'),
  },
  {
    id: 'religion',
    question: 'What is your cultural or religious background? (Select all that apply)',
    multi: true,
    options: [
      'Christian (Protestant)',
      'Catholic',
      'Jewish',
      'Muslim',
      'Hindu',
      'Buddhist',
      'Sikh',
      'Latter-day Saint (Mormon / LDS)',
      'Orthodox Christian',
      "Jehovah's Witness",
      'Pagan / Wiccan / Earth-based spirituality',
      'Spiritual but not religious',
      'Non-religious / Secular / Atheist / Agnostic',
      'Interfaith / Multiple traditions in our household',
      'Prefer not to say',
    ],
    hasRequestButton: true,
  },
  {
    id: 'religion_christian_detail',
    question: 'Which Christian tradition best describes you?',
    multi: true,
    options: [
      'Evangelical',
      'Baptist',
      'Pentecostal / Charismatic',
      'Non-denominational',
      'Methodist / Wesleyan',
      'Lutheran',
      'Episcopal / Anglican',
      'Reformed / Presbyterian',
      'Seventh-day Adventist',
      'Other Protestant',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['religion'] ?? []).includes('Christian (Protestant)'),
  },
  {
    id: 'religion_catholic_detail',
    question: 'What best describes your relationship with the Catholic faith?',
    multi: false,
    options: [
      'Practicing / active Catholic',
      'Cultural Catholic',
      'Traditional / Latin Mass Catholic',
      'Navigating disagreements with the Church',
      'Faith transition away from Catholicism',
    ],
    skipIf: (answers) => !(answers['religion'] ?? []).includes('Catholic'),
  },
  {
    id: 'religion_jewish_detail',
    question: 'Which Jewish movement or tradition?',
    multi: false,
    options: [
      'Orthodox',
      'Modern Orthodox',
      'Conservative / Masorti',
      'Reform / Progressive',
      'Reconstructionist / Renewal',
      'Cultural / Secular Jewish',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['religion'] ?? []).includes('Jewish'),
  },
  {
    id: 'religion_muslim_detail',
    question: 'Which Muslim tradition?',
    multi: false,
    options: [
      'Sunni',
      'Shia',
      'Sufi',
      'Ahmadiyya',
      'Cultural / non-practicing Muslim',
      'Prefer not to say',
    ],
    skipIf: (answers) => !(answers['religion'] ?? []).includes('Muslim'),
  },
  {
    id: 'religion_orthodox_detail',
    question: 'Which Orthodox tradition?',
    multi: false,
    options: [
      'Greek Orthodox',
      'Russian Orthodox',
      'Coptic Orthodox',
      'Ethiopian Orthodox',
      'Antiochian Orthodox',
      'Serbian / Bulgarian / Romanian Orthodox',
      'Other Eastern Orthodox',
    ],
    skipIf: (answers) => !(answers['religion'] ?? []).includes('Orthodox Christian'),
  },
  {
    id: 'religion_lds_detail',
    question: 'What best describes your relationship with the LDS church?',
    multi: false,
    options: [
      'Active / practicing member',
      'Cultural / less active LDS',
      'Navigating a faith transition',
      'LGBTQ+ LDS family',
    ],
    skipIf: (answers) => !(answers['religion'] ?? []).includes('Latter-day Saint (Mormon / LDS)'),
  },
  {
    id: 'home_language',
    question: 'What language(s) do you speak at home?',
    multi: true,
    options: [
      'English',
      'Spanish',
      'Mandarin Chinese',
      'Cantonese Chinese',
      'Hindi',
      'Arabic',
      'French',
      'Portuguese',
      'Tagalog / Filipino',
      'Vietnamese',
      'Korean',
      'Japanese',
      'Russian',
      'Italian',
      'German',
      'Haitian Creole',
      'Punjabi',
      'Urdu',
      'Bengali',
      'Tamil',
      'Farsi / Persian',
      'Polish',
      'Ukrainian',
      'Swahili',
      'Yoruba',
      'Amharic',
      'American Sign Language (ASL)',
      'Other',
    ],
    hasRequestButton: true,
  },
  {
    id: 'language_spanish_detail',
    question: 'Which Spanish-speaking community best describes your household?',
    multi: false,
    options: [
      'Mexican / Mexican-American',
      'Puerto Rican',
      'Cuban',
      'Dominican',
      'Central American (Guatemalan, Salvadoran, etc.)',
      'Colombian / Venezuelan / South American',
      'Castilian / Spanish (from Spain)',
      'Other / Mixed',
    ],
    skipIf: (answers) => !(answers['home_language'] ?? []).includes('Spanish'),
  },
  {
    id: 'language_arabic_detail',
    question: 'Which Arabic-speaking community best describes your household?',
    multi: false,
    options: [
      'Egyptian',
      'Levantine (Syrian, Lebanese, Palestinian, Jordanian)',
      'Gulf (Saudi, Emirati, Kuwaiti, Qatari, etc.)',
      'Maghrebi / North African (Moroccan, Algerian, Tunisian, Libyan)',
      'Iraqi',
      'Sudanese / East African Arabic',
      'Modern Standard Arabic / Mixed',
    ],
    skipIf: (answers) => !(answers['home_language'] ?? []).includes('Arabic'),
  },
  {
    id: 'language_portuguese_detail',
    question: 'Which Portuguese-speaking community best describes your household?',
    multi: false,
    options: [
      'Brazilian',
      'European (Portugal)',
      'African (Cape Verdean, Mozambican, Angolan, etc.)',
      'Other / Mixed',
    ],
    skipIf: (answers) => !(answers['home_language'] ?? []).includes('Portuguese'),
  },
  {
    id: 'language_multilingual',
    question: 'Are you planning to raise your children speaking multiple languages?',
    multi: false,
    options: [
      'Yes — intentionally raising bilingual / multilingual children',
      'Working on it / hoping to',
      'One language at home, learning another outside',
      'No / Not sure yet',
    ],
    skipIf: (answers) => {
      const langs = answers['home_language'] ?? [];
      return langs.filter(l => l !== 'Prefer not to say').length < 2;
    },
  },
  {
    id: 'housing_situation',
    question: 'What is your current housing situation?',
    multi: true,
    options: [
      'Homeowner',
      'Renting / Leasing',
      'Multigenerational household (living with family)',
      'Military housing / On base',
      'Tiny home / Van life / Alternative housing',
      'Rural property / Farm',
      'Experiencing housing instability',
      'In transition / Temporarily between homes',
    ],
    hasRequestButton: true,
  },
  {
    id: 'housing_homeowner_detail',
    question: 'What kind of home do you have?',
    multi: false,
    options: [
      'Suburban single-family home',
      'Urban / City home',
      'Condo / Townhouse / Row home',
      'Rural property',
      'Farm',
      'New construction / Just built',
      'First-time homeowner — still figuring it out!',
    ],
    skipIf: (answers) => !(answers['housing_situation'] ?? []).includes('Homeowner'),
  },
  {
    id: 'housing_renting_detail',
    question: 'What kind of rental are you in?',
    multi: false,
    options: [
      'Urban apartment',
      'Suburban apartment or complex',
      'House or townhouse rental',
      'Condo rental',
      'Saving up to buy',
    ],
    skipIf: (answers) => !(answers['housing_situation'] ?? []).includes('Renting / Leasing'),
  },
  {
    id: 'housing_multigenerational_detail',
    question: 'Who lives with you?',
    multi: true,
    options: [
      'My parents / my side of the family',
      "Partner's parents / in-laws",
      'Multiple generations (grandparents, parents, and children)',
      'Parents or in-laws in a separate attached unit or ADU',
    ],
    skipIf: (answers) => !(answers['housing_situation'] ?? []).includes('Multigenerational household (living with family)'),
  },
  {
    id: 'housing_alternative_detail',
    question: 'What kind of alternative housing?',
    multi: false,
    options: [
      'Tiny home',
      'Van life',
      'Skoolie (converted school bus)',
      'Full-time RV / travel trailer',
      'Off-grid / Earthship / Yurt',
    ],
    skipIf: (answers) => !(answers['housing_situation'] ?? []).includes('Tiny home / Van life / Alternative housing'),
  },
  {
    id: 'housing_instability_detail',
    question: 'What are you navigating?',
    multi: true,
    options: [
      'At risk of eviction',
      'Facing foreclosure',
      'Staying with others temporarily',
      'In a shelter or transitional housing',
      'Working toward stable housing',
      'Navigating housing assistance programs',
    ],
    hasRequestButton: true,
    skipIf: (answers) => !(answers['housing_situation'] ?? []).includes('Experiencing housing instability'),
  },
  {
    id: 'transportation',
    question: 'Do you have reliable transportation?',
    multi: true,
    options: [
      'Yes — I have a reliable car',
      'I use public transportation',
      'Limited or unreliable vehicle',
      'No car — I rely on rides from others',
      'No car — I live in a walkable / bikeable area',
      'No car — rural area with limited transit options',
      'Prefer not to say',
    ],
    hasRequestButton: true,
  },
  {
    id: 'transportation_public_detail',
    question: 'Which type of public transportation do you mainly use?',
    multi: true,
    options: [
      'City bus / local bus routes',
      'Metro / subway / light rail',
      'Commuter rail / regional train',
      'Paratransit / accessible transit service',
      'Limited routes — not many options where I live',
      'Multiple transfers needed to get anywhere with kids',
    ],
    skipIf: (answers) => !(answers['transportation'] ?? []).includes('I use public transportation'),
  },
  {
    id: 'transportation_unreliable_detail',
    question: 'What best describes your vehicle situation?',
    multi: true,
    options: [
      'One car shared between household members',
      'Car frequently needs repairs',
      'Saving up for a reliable car',
      'Recently lost access to a vehicle',
    ],
    skipIf: (answers) => !(answers['transportation'] ?? []).includes('Limited or unreliable vehicle'),
  },
  {
    id: 'location',
    question: 'Where do you live?',
    multi: false,
    options: [],
    type: 'location',
  },
];
