/*
  Provider Share View — Deployed as a Supabase Edge Function.

  Public, unauthenticated endpoint: a pediatrician opens this link with no
  Supabase session at all, so it MUST be deployed with JWT verification
  disabled:

    supabase functions deploy provider-share-view --no-verify-jwt

  It resolves a Doctor Visit Prep share token to a read-only summary page.
  The token itself is the only credential — we hash whatever comes in on
  ?token= and compare against provider_shares.share_token_hash using the
  service-role key (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are both
  auto-provided as edge function secrets). RLS never grants this table to
  anon/authenticated clients directly — only this function's service-role
  key can resolve a token to data, and only for tokens that still exist
  and haven't expired.
*/

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface VisitSummarySnapshot {
  babyName: string;
  visitType: string;
  visitDate: string;
  rangeDays: number;
  generatedAt: string;
  feedingLine: string;
  sleepLine: string;
  concerns: string[];
  questions: string[];
  growthRows: { date: string; weight: string; height: string }[];
}

async function sha256hex(message: string): Promise<string> {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(message));
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

function esc(s: string | null | undefined): string {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function htmlPage(title: string, body: string, status = 200): Response {
  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(title)}</title>
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #222; padding: 24px; max-width: 640px; margin: 0 auto; background: #fafafa; }
    h1 { font-size: 20px; margin-bottom: 4px; }
    h2 { font-size: 15px; margin-top: 24px; border-bottom: 2px solid #eee; padding-bottom: 4px; color: #333; }
    .sub { color: #666; font-size: 13px; margin-bottom: 20px; }
    ul { padding-left: 20px; margin: 8px 0; }
    li { margin-bottom: 4px; font-size: 14px; line-height: 1.4; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { text-align: left; padding: 6px 8px; font-size: 13px; border-bottom: 1px solid #eee; }
    th { color: #555; font-weight: 600; }
    .footer { margin-top: 32px; color: #999; font-size: 11px; border-top: 1px solid #eee; padding-top: 12px; }
    .card { background: #fff; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  </style>
</head>
<body>
  <div class="card">${body}</div>
</body>
</html>`;
  return new Response(html, { status, headers: { ...corsHeaders, 'Content-Type': 'text/html; charset=utf-8' } });
}

function expiredPage(): Response {
  return htmlPage(
    'Link expired',
    `<h1>This link has expired</h1><p>Doctor Visit Prep links are only valid for 24 hours. Ask the parent to generate a new summary link.</p>`,
    404,
  );
}

function renderSummary(s: VisitSummarySnapshot): string {
  const concernsList = s.concerns.length
    ? `<ul>${s.concerns.map(c => `<li>${esc(c)}</li>`).join('')}</ul>`
    : '<p>No concerns logged in this window.</p>';
  const questionsList = s.questions.length
    ? `<ul>${s.questions.map(q => `<li>${esc(q)}</li>`).join('')}</ul>`
    : '';
  const growthTable = s.growthRows.length
    ? `<table><thead><tr><th>Date</th><th>Weight</th><th>Height</th></tr></thead><tbody>${
        s.growthRows.map(r => `<tr><td>${esc(r.date)}</td><td>${esc(r.weight)}</td><td>${esc(r.height)}</td></tr>`).join('')
      }</tbody></table>`
    : '';

  return `
    <h1>${esc(s.babyName)}'s Visit Summary</h1>
    <div class="sub">${esc(s.visitType)} · ${esc(s.visitDate)} · Last ${s.rangeDays} days</div>

    <h2>Feeding</h2>
    <p>${esc(s.feedingLine)}</p>

    <h2>Sleep</h2>
    <p>${esc(s.sleepLine)}</p>

    <h2>Concerns Logged</h2>
    ${concernsList}

    ${growthTable ? `<h2>Growth</h2>${growthTable}` : ''}

    ${questionsList ? `<h2>Questions You Might Ask</h2>${questionsList}` : ''}

    <div class="footer">Generated by Parent Patch on ${esc(new Date(s.generatedAt).toLocaleDateString())} · Read-only, expires 24 hours after creation</div>
  `;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  const url = new URL(req.url);
  const token = url.searchParams.get('token') ?? '';
  if (!token) return expiredPage();

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
  const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
  if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    return htmlPage('Unavailable', '<h1>Temporarily unavailable</h1><p>Please try again shortly.</p>', 503);
  }

  const tokenHash = await sha256hex(token);

  try {
    const lookupRes = await fetch(
      `${SUPABASE_URL}/rest/v1/provider_shares?share_token_hash=eq.${tokenHash}&select=id,data_snapshot,expires_at,accessed_at`,
      { headers: { apikey: SERVICE_ROLE_KEY, Authorization: `Bearer ${SERVICE_ROLE_KEY}` } },
    );
    const rows = await lookupRes.json();
    const share = rows?.[0];

    if (!share || new Date(share.expires_at) < new Date()) return expiredPage();

    if (!share.accessed_at) {
      await fetch(`${SUPABASE_URL}/rest/v1/provider_shares?id=eq.${share.id}`, {
        method: 'PATCH',
        headers: {
          apikey: SERVICE_ROLE_KEY,
          Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
          'Content-Type': 'application/json',
          Prefer: 'return=minimal',
        },
        body: JSON.stringify({ accessed_at: new Date().toISOString() }),
      });
    }

    return htmlPage(`${share.data_snapshot?.babyName ?? 'Baby'}'s Visit Summary`, renderSummary(share.data_snapshot));
  } catch {
    return htmlPage('Unavailable', '<h1>Temporarily unavailable</h1><p>Please try again shortly.</p>', 503);
  }
});
